name: Deploy na VPS (Docker)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: Deploy via SSH (Docker)
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: githubactions
          VPS_PORT: ${{ secrets.VPS_PORT || '22' }}
        run: |
          ssh -o StrictHostKeyChecking=no -p "$VPS_PORT" "$VPS_USER"@"$VPS_HOST" '
            set -e
            cd /srv/painelcommunityv2
            git pull origin main
            docker compose pull || true
            docker compose build
            docker compose up -d --remove-orphans
          '

# Ajuste /caminho/para/painelcommunityv2 para o diretório do projeto na sua VPS
# Certifique-se de que docker e docker compose estão instalados e configurados na VPS
# Adicione VPS_HOST, VPS_KEY e (opcional) VPS_PORT nos secrets do GitHub 